var PAYMENT_STATUS = {
	APPROVED : 'APPROVED',
	DECLINED : 'DECLINED',
	FAILED : 'FAILED',
	PENDING : 'PENDING',
	SUCCESS : 'SUCCESS',
	UNKNOWN: 'Payment was Declined by Afterpay'
}

var PAYMENT_MODE = 	{
	PAYMENT_METHOD : 'AFTERPAY_PBI',
	DIRECT_CAPTURE : 'DIRECT_CAPTURE',
	AUTHORISE : "AUTHORISE"
}

var CONFIGURATION_TYPE = {
	PAY_BY_INSTALLMENT : 'PAY_BY_INSTALLMENT'
}

module.exports.PAYMENT_STATUS = PAYMENT_STATUS;
module.exports.PAYMENT_MODE = PAYMENT_MODE;
module.exports.CONFIGURATION_TYPE = CONFIGURATION_TYPE;